id: A674024D8
title: The Single Mind Kīla Practice, Part of the 'Neck-Pouch Dagger’ (Purba Gulkhukma)
  Cycle
type: translation
pechas:
- IA48A43A8
- IB1775785
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:51:00.693199
  last_modified_at: 2023-01-04 12:51:00.693220
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  IA48A43A8/8D71: DFD2
  IB1775785/4A65: DFD2
